/home/chri3448/EPDF_ABC/gc_jobs/../astroLFI/LFI_galactic_center.py:416: RuntimeWarning: invalid value encountered in arccos
  earth_angles[:,1] = np.arccos(x/distances/np.sin(earth_angles[:,0]))
Traceback (most recent call last):
astroLFI/LFI_galactic_center.py:416: RuntimeWarning: invalid value encountered in arccos
  earth_angles[:,1] = np.arccos(x/distances/np.sin(earth_angles[:,0]))
Traceback (most recent call last):
astroLFI/LFI_galactic_center.py:416: RuntimeWarning: invalid value encountered in arccos
  earth_angles[:,1] = np.arccos(x/distances/np.sin(earth_angles[:,0]))
Traceback (most recent call last):
astroLFI/LFI_galactic_center.py:416: RuntimeWarning: invalid value encountered in arccos
  earth_angles[:,1] = np.arccos(x/distances/np.sin(earth_angles[:,0]))
Traceback (most recent call last):
astroLFI/LFI_galactic_center.py:416: RuntimeWarning: invalid value encountered in arccos
  earth_angles[:,1] = np.arccos(x/distances/np.sin(earth_angles[:,0]))
Traceback (most recent call last):
astroLFI/LFI_galactic_center.py:416: RuntimeWarning: invalid value encountered in arccos
  earth_angles[:,1] = np.arccos(x/distances/np.sin(earth_angles[:,0]))
Traceback (most recent call last):
jobs/jobs/run6_poisson.py", line 241, in <module>
    theta, x = run_sims(num_sims = 100)
  File "/home/chri3448/EPDF_ABC/gc_jobs/jobs/run6_poisson.py", line 232, in run_sims
    simulator, prior = prepare_for_sbi(simulator, prior)
  File "/home/chri3448/.local/lib/python3.10/site-packages/sbi/utils/user_input_checks.py", line 629, in prepare_for_sbi
    check_sbi_inputs(simulator, prior)
  File "/home/chri3448/.local/lib/python3.10/site-packages/sbi/utils/user_input_checks.py", line 646, in check_sbi_inputs
    simulation = simulator(theta)
  File "/home/chri3448/.local/lib/python3.10/site-packages/sbi/utils/user_input_checks.py", line 551, in batch_loop_simulator
    xs = list(map(simulator, theta))
  File "/home/chri3448/.local/lib/python3.10/site-packages/sbi/utils/user_input_checks.py", line 515, in pytorch_simulator
    return torch.as_tensor(simulator(theta), dtype=float32)
  File "/home/chri3448/EPDF_ABC/gc_jobs/jobs/run6_poisson.py", line 218, in simulator
    photon_info = my_LFI.generate_photons_from_sources(params, source_info, grains = 1000)
  File "/home/chri3448/EPDF_ABC/gc_jobs/../astroLFI/LFI_galactic_center.py", line 581, in generate_photons_from_sources
    map_vals, map_E, map_i, N_side = self.abun_lum_spec[si][0](input_params)
  File "/home/chri3448/EPDF_ABC/gc_jobs/jobs/run6_poisson.py", line 133, in DM_wrap
    cross_sec = params[start3_i + 1]*1e-26 #cm^3 s^-1
IndexError: index 2 is out of bounds for axis 0 with size 2
/home/chri3448/EPDF_ABC/gc_jobs/../astroLFI/LFI_galactic_center.py:416: RuntimeWarning: invalid value encountered in arccos
  earth_angles[:,1] = np.arccos(x/distances/np.sin(earth_angles[:,0]))
Traceback (most recent call last):
  File "/home/chri3448/EPDF_ABC/gc_jobs/jobs/run6_poisson.py", line 241, in <module>
    theta, x = run_sims(num_sims = 100)
  File "/home/chri3448/EPDF_ABC/gc_jobs/jobs/run6_poisson.py", line 232, in run_sims
    simulator, prior = prepare_for_sbi(simulator, prior)
  File "/home/chri3448/.local/lib/python3.10/site-packages/sbi/utils/user_input_checks.py", line 629, in prepare_for_sbi
    check_sbi_inputs(simulator, prior)
  File "/home/chri3448/.local/lib/python3.10/site-packages/sbi/utils/user_input_checks.py", line 646, in check_sbi_inputs
    simulation = simulator(theta)
  File "/home/chri3448/.local/lib/python3.10/site-packages/sbi/utils/user_input_checks.py", line 551, in batch_loop_simulator
    xs = list(map(simulator, theta))
  File "/home/chri3448/.local/lib/python3.10/site-packages/sbi/utils/user_input_checks.py", line 515, in pytorch_simulator
    return torch.as_tensor(simulator(theta), dtype=float32)
  File "/home/chri3448/EPDF_ABC/gc_jobs/jobs/run6_poisson.py", line 218, in simulator
    photon_info = my_LFI.generate_photons_from_sources(params, source_info, grains = 1000)
  File "/home/chri3448/EPDF_ABC/gc_jobs/../astroLFI/LFI_galactic_center.py", line 581, in generate_photons_from_sources
    map_vals, map_E, map_i, N_side = self.abun_lum_spec[si][0](input_params)
  File "/home/chri3448/EPDF_ABC/gc_jobs/jobs/run6_poisson.py", line 133, in DM_wrap
    cross_sec = params[start3_i + 1]*1e-26 #cm^3 s^-1
IndexError: index 2 is out of bounds for axis 0 with size 2
  File "/home/chri3448/EPDF_ABC/gc_jobs/jobs/run6_poisson.py", line 241, in <module>
    theta, x = run_sims(num_sims = 100)
  File "/home/chri3448/EPDF_ABC/gc_jobs/jobs/run6_poisson.py", line 232, in run_sims
    simulator, prior = prepare_for_sbi(simulator, prior)
  File "/home/chri3448/.local/lib/python3.10/site-packages/sbi/utils/user_input_checks.py", line 629, in prepare_for_sbi
    check_sbi_inputs(simulator, prior)
  File "/home/chri3448/.local/lib/python3.10/site-packages/sbi/utils/user_input_checks.py", line 646, in check_sbi_inputs
    simulation = simulator(theta)
  File "/home/chri3448/.local/lib/python3.10/site-packages/sbi/utils/user_input_checks.py", line 551, in batch_loop_simulator
    xs = list(map(simulator, theta))
  File "/home/chri3448/.local/lib/python3.10/site-packages/sbi/utils/user_input_checks.py", line 515, in pytorch_simulator
    return torch.as_tensor(simulator(theta), dtype=float32)
  File "/home/chri3448/EPDF_ABC/gc_jobs/jobs/run6_poisson.py", line 218, in simulator
    photon_info = my_LFI.generate_photons_from_sources(params, source_info, grains = 1000)
  File "/home/chri3448/EPDF_ABC/gc_jobs/../astroLFI/LFI_galactic_center.py", line 581, in generate_photons_from_sources
    map_vals, map_E, map_i, N_side = self.abun_lum_spec[si][0](input_params)
  File "/home/chri3448/EPDF_ABC/gc_jobs/jobs/run6_poisson.py", line 133, in DM_wrap
    cross_sec = params[start3_i + 1]*1e-26 #cm^3 s^-1
IndexError: index 2 is out of bounds for axis 0 with size 2
  File "/home/chri3448/EPDF_ABC/gc_jobs/jobs/run6_poisson.py", line 241, in <module>
    theta, x = run_sims(num_sims = 100)
  File "/home/chri3448/EPDF_ABC/gc_jobs/jobs/run6_poisson.py", line 232, in run_sims
    simulator, prior = prepare_for_sbi(simulator, prior)
  File "/home/chri3448/.local/lib/python3.10/site-packages/sbi/utils/user_input_checks.py", line 629, in prepare_for_sbi
    check_sbi_inputs(simulator, prior)
  File "/home/chri3448/.local/lib/python3.10/site-packages/sbi/utils/user_input_checks.py", line 646, in check_sbi_inputs
    simulation = simulator(theta)
  File "/home/chri3448/.local/lib/python3.10/site-packages/sbi/utils/user_input_checks.py", line 551, in batch_loop_simulator
    xs = list(map(simulator, theta))
  File "/home/chri3448/.local/lib/python3.10/site-packages/sbi/utils/user_input_checks.py", line 515, in pytorch_simulator
    return torch.as_tensor(simulator(theta), dtype=float32)
  File "/home/chri3448/EPDF_ABC/gc_jobs/jobs/run6_poisson.py", line 218, in simulator
    photon_info = my_LFI.generate_photons_from_sources(params, source_info, grains = 1000)
  File "/home/chri3448/EPDF_ABC/gc_jobs/../astroLFI/LFI_galactic_center.py", line 581, in generate_photons_from_sources
    map_vals, map_E, map_i, N_side = self.abun_lum_spec[si][0](input_params)
  File "/home/chri3448/EPDF_ABC/gc_jobs/jobs/run6_poisson.py", line 133, in DM_wrap
    cross_sec = params[start3_i + 1]*1e-26 #cm^3 s^-1
IndexError: index 2 is out of bounds for axis 0 with size 2
  File "/home/chri3448/EPDF_ABC/gc_jobs/jobs/run6_poisson.py", line 241, in <module>
    theta, x = run_sims(num_sims = 100)
  File "/home/chri3448/EPDF_ABC/gc_jobs/jobs/run6_poisson.py", line 232, in run_sims
    simulator, prior = prepare_for_sbi(simulator, prior)
  File "/home/chri3448/.local/lib/python3.10/site-packages/sbi/utils/user_input_checks.py", line 629, in prepare_for_sbi
    check_sbi_inputs(simulator, prior)
  File "/home/chri3448/.local/lib/python3.10/site-packages/sbi/utils/user_input_checks.py", line 646, in check_sbi_inputs
    simulation = simulator(theta)
  File "/home/chri3448/.local/lib/python3.10/site-packages/sbi/utils/user_input_checks.py", line 551, in batch_loop_simulator
    xs = list(map(simulator, theta))
  File "/home/chri3448/.local/lib/python3.10/site-packages/sbi/utils/user_input_checks.py", line 515, in pytorch_simulator
    return torch.as_tensor(simulator(theta), dtype=float32)
  File "/home/chri3448/EPDF_ABC/gc_jobs/jobs/run6_poisson.py", line 218, in simulator
    photon_info = my_LFI.generate_photons_from_sources(params, source_info, grains = 1000)
  File "/home/chri3448/EPDF_ABC/gc_jobs/../astroLFI/LFI_galactic_center.py", line 581, in generate_photons_from_sources
    map_vals, map_E, map_i, N_side = self.abun_lum_spec[si][0](input_params)
  File "/home/chri3448/EPDF_ABC/gc_jobs/jobs/run6_poisson.py", line 133, in DM_wrap
    cross_sec = params[start3_i + 1]*1e-26 #cm^3 s^-1
IndexError: index 2 is out of bounds for axis 0 with size 2
  File "/home/chri3448/EPDF_ABC/gc_jobs/jobs/run6_poisson.py", line 241, in <module>
    theta, x = run_sims(num_sims = 100)
  File "/home/chri3448/EPDF_ABC/gc_jobs/jobs/run6_poisson.py", line 232, in run_sims
    simulator, prior = prepare_for_sbi(simulator, prior)
  File "/home/chri3448/.local/lib/python3.10/site-packages/sbi/utils/user_input_checks.py", line 629, in prepare_for_sbi
    check_sbi_inputs(simulator, prior)
  File "/home/chri3448/.local/lib/python3.10/site-packages/sbi/utils/user_input_checks.py", line 646, in check_sbi_inputs
    simulation = simulator(theta)
  File "/home/chri3448/.local/lib/python3.10/site-packages/sbi/utils/user_input_checks.py", line 551, in batch_loop_simulator
    xs = list(map(simulator, theta))
  File "/home/chri3448/.local/lib/python3.10/site-packages/sbi/utils/user_input_checks.py", line 515, in pytorch_simulator
    return torch.as_tensor(simulator(theta), dtype=float32)
  File "/home/chri3448/EPDF_ABC/gc_jobs/jobs/run6_poisson.py", line 218, in simulator
    photon_info = my_LFI.generate_photons_from_sources(params, source_info, grains = 1000)
  File "/home/chri3448/EPDF_ABC/gc_jobs/../astroLFI/LFI_galactic_center.py", line 581, in generate_photons_from_sources
    map_vals, map_E, map_i, N_side = self.abun_lum_spec[si][0](input_params)
  File "/home/chri3448/EPDF_ABC/gc_jobs/jobs/run6_poisson.py", line 133, in DM_wrap
    cross_sec = params[start3_i + 1]*1e-26 #cm^3 s^-1
IndexError: index 2 is out of bounds for axis 0 with size 2
  File "/home/chri3448/EPDF_ABC/gc_jobs/jobs/run6_poisson.py", line 241, in <module>
    theta, x = run_sims(num_sims = 100)
  File "/home/chri3448/EPDF_ABC/gc_jobs/jobs/run6_poisson.py", line 232, in run_sims
    simulator, prior = prepare_for_sbi(simulator, prior)
  File "/home/chri3448/.local/lib/python3.10/site-packages/sbi/utils/user_input_checks.py", line 629, in prepare_for_sbi
    check_sbi_inputs(simulator, prior)
  File "/home/chri3448/.local/lib/python3.10/site-packages/sbi/utils/user_input_checks.py", line 646, in check_sbi_inputs
    simulation = simulator(theta)
  File "/home/chri3448/.local/lib/python3.10/site-packages/sbi/utils/user_input_checks.py", line 551, in batch_loop_simulator
    xs = list(map(simulator, theta))
  File "/home/chri3448/.local/lib/python3.10/site-packages/sbi/utils/user_input_checks.py", line 515, in pytorch_simulator
    return torch.as_tensor(simulator(theta), dtype=float32)
  File "/home/chri3448/EPDF_ABC/gc_jobs/jobs/run6_poisson.py", line 218, in simulator
    photon_info = my_LFI.generate_photons_from_sources(params, source_info, grains = 1000)
  File "/home/chri3448/EPDF_ABC/gc_jobs/../astroLFI/LFI_galactic_center.py", line 581, in generate_photons_from_sources
    map_vals, map_E, map_i, N_side = self.abun_lum_spec[si][0](input_params)
  File "/home/chri3448/EPDF_ABC/gc_jobs/jobs/run6_poisson.py", line 133, in DM_wrap
    cross_sec = params[start3_i + 1]*1e-26 #cm^3 s^-1
IndexError: index 2 is out of bounds for axis 0 with size 2
